name: build
on:
  release:
    types: [created]
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          binary_name: job_metrics_exporter-${{ github.run_number }}
          asset_name: job_metrics_exporter-${{ github.run_number }}.tar.gz
          release_tag: ${{ github.ref }}
          release_name: Release ${{ github.run_number }}
          overwrite: true  # Set this to true if you want to overwrite existing assets
          upload: true
