name: build and test on commit
on: 
  push: 
    branches: 
      - 'production'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22.2'
      - uses: wangyoucao577/go-release-action@v1
      - name: Get Dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test 
        run: go test -v ./...
      
  
